source "https://rubygems.org"

gem "fastlane"
gem "fastlane-plugin-increment_version_code"
gem "fastlane-plugin-increment_version_name"
gem "fastlane-plugin-sentry"
gem "fastlane-plugin-versioning_android"
