import ('../ios/fastlane/Fastfile')
import ('../android/fastlane/Fastfile')

lane :checkIfRelease do
  env = sh("cat ../.env | grep APP_ENV")
  env = env.split("=")[1].strip
  
  if env === "debug"
    UI.user_error!("Remember to change APP_ENV to \"release\"")
  end
end

lane :incrementJsonBuildNumber do
  puts "Change package.json build number"
  system("cd .. && jq -e '.build += 1' 'package.json' > 'package.json.tmp' && cp package.json.tmp package.json && rm -f package.json.tmp")
end

lane :gitUpdate do
  version = lane_context[SharedValues::VERSION_NUMBER]
  build_number = lane_context[SharedValues::BUILD_NUMBER]

  tagName = version+"+"+build_number
  commitMessage="Auto commit version "+tagName
  git_add(path: ".")
  git_commit(path: ".", message: commitMessage)
  add_git_tag(
    tag: tagName
  )
  push_to_git_remote(
    remote: "origin",         # optional, default: "origin"
    local_branch: "master",  # optional, aliased by "branch", default is set to current branch
    remote_branch: "master", # optional, default is set to local_branch
    force: true,    # optional, default: false
    force_with_lease: true,   # optional, default: false
    tags: true,    # optional, default: true
    no_verify: true,# optional, default: false
    set_upstream: true        # optional, default: false
  )
end

lane :versionAndBuildUpdate do
  checkIfRelease
  incrementJsonBuildNumber

  # From ios fastfile
  updateIOSBuildVersionAndNumber
  # From android fastfile
  updateAndroidBuildVersionAndNumber

  gitUpdate
end

