default_platform(:ios)

platform :ios do
  lane :beta do
    match(type: 'appstore', readonly: true)
    
    increment_build_number(xcodeproj: "ToPetOrNot.xcodeproj")
    gym(scheme: "ToPetOrNot", configuration: "Release")

    upload_to_testflight(username: ENV['FASTLANE_USER'], skip_waiting_for_build_processing: true)    
  end
end
