default_platform(:android)

platform :android do
  lane :betaAndroid do
    increment_version_code(
      gradle_file_path: './app/build.gradle',
    )

    store_password = ENV['STORE_PASSWORD']
    key_password = ENV['KEY_PASSWORD']
    releaseFilePath = File.join(Dir.pwd, "..", "/secret-key/secret.keystore")

    gradle(task: 'clean')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => store_password,
        "android.injected.signing.key.alias" => ENV['MY_KEY_ALIAS'],
        "android.injected.signing.key.password" => key_password,
      }
    )
    upload_to_play_store(
      track: 'internal',
      track_promote_to: 'alpha'
    )
  end
end
