default_platform(:android)

lane :updateAndroidBuildVersionAndNumber do
  package = load_json(json_path: "package.json")
  increment_version_code(gradle_file_path: 'android/app/build.gradle', version_code: package["build"])
  increment_version_name(gradle_file_path: 'android/app/build.gradle', version_name: package["version"])
end

lane :betaAndroid do
  store_password = ENV['STORE_PASSWORD']
  key_password = ENV['KEY_PASSWORD']
  releaseFilePath = File.join(Dir.pwd, "..", "/secret-key/secret.keystore")

  gradle(task: 'clean')
  gradle(
    task: 'bundle',
    build_type: 'Release',
    print_command: false,
    properties: {
      "android.injected.signing.store.file" => releaseFilePath,
      "android.injected.signing.store.password" => store_password,
      "android.injected.signing.key.alias" => ENV['MY_KEY_ALIAS'],
      "android.injected.signing.key.password" => key_password,
    }
  )
  upload_to_play_store(
    track: 'internal',
    track_promote_to: 'alpha'
  )
end

